# Generated by Django 4.1.7 on 2023-03-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_rename_categoria_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricão', models.CharField(max_length=100)),
            ],
        ),
    ]
